# Generated by Django 3.2.2 on 2021-05-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True),
        ),
    ]
